### ISSUE TITLE
Invalid CSRF token on First Connection

### ISSUE THREAD

**Issue by BrianMoos** [benjaminjonard/koillection#341]
Using docker-compose with standard settings.

I get the following error when trying to create a user.
**_The CSRF token is invalid. Please try to resubmit the form._**

![image](https://user-images.githubusercontent.com/11622742/119232836-e3353b00-bb26-11eb-83ba-a33f97b3ae11.png)

Also the Date format/Time zone looks a little off.

**Comment by benjaminjonard** [comment]
Hello, I published a new version (1.2.2) to fix the date and timezone lists. Could you try again please ? I couldn't reproduce your problem with csrf

**Comment by BrianMoos** [comment]
The date and time zone looks better (but I'm missing my favorite format: ISO-8601; yyyy-mm-dd)

The CSRF token issue persists. 

I have tried the docker image for v1.1.7 and that works - something must've changed since then.
I'm not familiar with Symfony so I have no idea of where to look for the relevant changes.

**Comment by benjaminjonard** [comment]
For the date format, it seems to be an label mistake, if you select yyyy-dd-mm it should behave as yyyy-mm-dd. I'll push a fix soon.

Could you share your docker-compose file and koillection logs when starting the container ? I'll do some tests as soon as possible, but I'm not home this week

**Comment by BrianMoos** [comment]
Thanks for looking into this.
I've recently changed to another host machine but the issue is the same.

My docker-compose.yaml looks like this:

```
version: '3'

services:
    # Koillection
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        ports:
            - 8002:80
        environment:
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_VERSION=12.2
            - PHP_TZ=Europe/Copenhagen
        depends_on:
            - db
        volumes:
            - /docker/koillection/conf:/conf
            - /docker/koillection/uploads:/uploads

    # Database : choose one of the following
    db:
        image: postgres:latest
        container_name: db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        volumes:
            - "/docker/koillection/postgresql:/var/lib/postgresql/data"

```

I'm not sure what you mean by koillection logs but this are the output of `docker-compose up` :

```
bml@srv01:/docker/koillection$ docker-compose up
Creating db ... done
Creating koillection ... done
Attaching to db, koillection
db             |
db             | PostgreSQL Database directory appears to contain a database; Skipping initialization
db             |
koillection    | **** Make sure the /conf and /uploads folders exist ****
koillection    | **** Create the symbolic link for the /uploads folder ****
db             | 2021-05-29 17:54:23.554 UTC [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db             | 2021-05-29 17:54:23.554 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db             | 2021-05-29 17:54:23.554 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db             | 2021-05-29 17:54:23.559 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db             | 2021-05-29 17:54:23.566 UTC [26] LOG:  database system was shut down at 2021-05-29 17:54:17 UTC
db             | 2021-05-29 17:54:23.572 UTC [1] LOG:  database system is ready to accept connections
koillection    | **** Copy the .env to /conf ****
koillection    | **** Inject .env values ****
koillection    | **** Migrate the database ****
koillection    | [notice] Migrating up to App\Migrations\Postgresql\Version20210514101359
koillection    | [error] Migration App\Migrations\Mysql\Version20200429093452 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [error] Migration App\Migrations\Mysql\Version20200727114843 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [error] Migration App\Migrations\Mysql\Version20200812160901 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [error] Migration App\Migrations\Mysql\Version20200923193955 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [error] Migration App\Migrations\Mysql\Version20201010121132 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [error] Migration App\Migrations\Mysql\Version20201215214207 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [error] Migration App\Migrations\Mysql\Version20210127105342 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [error] Migration App\Migrations\Mysql\Version20210514100228 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
koillection    | [notice] finished in 13.7ms, used 42.5M memory, 8 migrations executed, 0 sql queries
koillection    |
koillection    | **** Create user and use PUID/PGID ****
koillection    | -e     User UID :      1000
koillection    | -e     User GID :      1000
koillection    | **** Set Permissions ****
koillection    | **** Create nginx log files ****
koillection    | **** Setup complete, starting the server. ****

```

**Comment by benjaminjonard** [comment]
Hello, 

Sorry I couldn't reproduce your error, even when using your docker-compose.yml 

Which browser are you using ? (and which version if possible). 
Also could you take a look at this answer from stack overflow please ? https://stackoverflow.com/a/48913691

I will do some more research on my side

**Comment by BrianMoos** [comment]
I've tried in Brave, Chrome, and Edge - yes, they are all Chromium-based browsers so they might not behave very different.

Anything I should look for in the symfony profiler?
![image](https://user-images.githubusercontent.com/11622742/120082302-6ecc4000-c0c2-11eb-9ab2-942566b72851.png)

**Comment by lopiv2** [comment]
I still have the same problem. Installed with Docker, and The CSRF token is invalid. Please try to resubmit the form.

**Comment by benjaminjonard** [comment]
Hello, this one is hard for me to fix because I can't reproduce it.

I've searched a bit and it could be linked to session not being able to be created because of the domain where the code is running. The problem would only appear for certain users.

I will rewrite the auth process and the token validation during the next few days. 
If that still doesn't work, I will add an option to disable CSRF tokens (not ideal, but I guess risk is pretty limited for this website)

**Comment by lopiv2** [comment]
I haven't done anything special. Just creating a docker compose and executing It. No reverse proxy, nothing. And in the first run, the error appears. I assume that the user and password are those i use to Connect to the database MySQL, Because there are no indications anywhere around about It....

**Comment by benjaminjonard** [comment]
Could you share your docker-compose.yml file please ? 
Also, do yo run the code on a server or on localhost ? 

For the username/password, if your database has no user it should prompt you the "First connection" form, where you can create a new user with your own credentials

**Comment by lopiv2** [comment]
```
koillection:
    image: koillection/koillection
    container_name: koillection
    restart: unless-stopped
    ports:
      - 8088:80
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - DB_DRIVER=pdo_mysql
        - DB_NAME=koillection
        - DB_HOST=mariadb
        - DB_PORT=3306
        - DB_USER=****
        - DB_PASSWORD=******
        - DB_VERSION=12.2
        - PHP_TZ=Europe/Madrid
    depends_on:
        - mariadb
    networks:
      - traefik_proxy
    volumes:
        - /cloud/cloud/koillection/conf:/conf
        - /cloud/cloud/koillection/uploads:/uploads
```
As you see, nothing special at all

**Comment by benjaminjonard** [comment]
Ok, your configuration is working for me. This seems to be a problem related on how the website is hosted.
Do you use https ? And what does the url where Koillection responds looks like ? (do you have a subdomain like koillection.mydomain.com)

Also I'm sorry but right now Koillection is not compatible with MariaDB (see #253)

**Comment by lopiv2** [comment]
Have a traefik one, with subdomains, but not configured with koillection yet. By the moment Im doing some test with local IP HTTP, 192.168.1.xxx:8088. And about MARIADB, cant tell you if is not working, because as i already have the CSRF problem, i haven´t done any test with creating collections or so...

**Comment by daknin** [comment]
I think I'm also experiencing this issue. I'm basically using the docker-compose at https://github.com/koillection/koillection-docker with postgres and a port mapping of 7080:80. If I access using http://myserver.mydomain.com:7080 I get the CSRF error, if I use http://localhost:7080 I don't get the CSRF error.

**Comment by benjaminjonard** [comment]
Hello, 

I can see the error depends on the domain, but I fail to reproduce. 
I tried to fix it but can't try it myself, could you use the image  `koillection/koillection:beta` instead of `koillection/koillection` in your docker-compose.yml and tell me if you see a difference ? 

Thanks

**Comment by daknin** [comment]
I still get the error using `koillection/koillection:beta`. I did a bit of investigation, if I don't use localhost it looks like a new session is being created for every request because the browser refuses the set the PHPSESSID cookie. If this is the case then the new session won't contain the csrf token which was added the the old session.

![image](https://user-images.githubusercontent.com/810653/133438517-e82f7d2f-8071-4fb3-a253-1c965a6430a4.png)

**Comment by benjaminjonard** [comment]
Thank you very much for your answer, I think I understand what's happening. 

Could you update your image (with `docker-compose pull`) and add `HTTPS_ENABLED=0` in the environment variables in your docker-compose.yml ? 

It should look like this :

```
services:
      # Koillection
      koillection:
          image: koillection/koillection
          container_name: koillection
          restart: unless-stopped
          ports:
              - 80:80
          environment:
              - DB_DRIVER=pdo_pgsql 
              - DB_NAME=koillection
              - DB_HOST=db
              - DB_PORT=5432
              - DB_USER=root
              - DB_PASSWORD=root
              - DB_VERSION=12.2
              - PHP_TZ=Europe/Paris
              - HTTPS_ENABLED=0
          depends_on:
              - db
          volumes:
              - ./docker/volumes/koillection/conf:/conf
              - ./docker/volumes/koillection/uploads:/uploads
```

**Comment by daknin** [comment]
I tried using `koillection/koillection:beta` and it now works.

**Comment by lopiv2** [comment]
With beta version is fixed for me. Only problem is MariaDB in my case, which is not working, but this is a known failure. Will try with Postgresql tomorrow and see the results....Thank you for the fix anyway.

**Comment by benjaminjonard** [comment]
I published a new release of Koillection. Switching back from `koillection/koillection:beta` to `koillection/koillection` should be working now.

Thank you for your help fixing this bug.

**Comment by erikabourque** [comment]
Hello, just wanted to let you know that I reproduced this bug in the latest and beta versions of the docker version, however I managed to get around it by using https instead of http

**Comment by benjaminjonard** [comment]
Hello, thanks for letting me know. Just to be sure, did you use the HTTPS_ENABLED=0 option in your docker-compose file ?

**Comment by erikabourque** [comment]
I have HTTP_ENABLED=1

**Comment by benjaminjonard** [comment]
Ok, it should be why it isn't working with http. If you prefer to use http then you have to change the value to HTTPS_ENABLED=0
