### ISSUE TITLE
Docker Container Remains Unhealthy

### ISSUE THREAD

**Issue by ItsNoted** [benjaminjonard/koillection#448]
I'm a bit weary to use the docker image because when I deploy it, I keep getting this error:

`[23-Jul-2022 16:42:55] NOTICE: PHP message: PHP Warning:  Can't preload already declared class ReflectionEnum in /var/www/koillection/vendor/laminas/laminas-code/polyfill/ReflectionEnumPolyfill.php on line 8`

And the docker container remains unhealthy.

I am not sure what is causing this.

**Comment by benjaminjonard** [comment]
I'll have a look into why the container appears unhealthy. 

But otherwise this message can be safely ignored, it's only informative (preloading is a way to make some PHP code faster, its not a problem if something is skipped, it's optional)

**Comment by benjaminjonard** [comment]
I published a new version of the docker image that fixes the problem. 

I made a mistake when updating the image last week. In an effort to make the image as lightweight as possible I uninstalled some dependencies from the image and I removed curl, forgetting it was necessary for performing the healthcheck

**Comment by dafaras** [comment]
I am still seeing the same error
[28-Jul-2022 20:44:44] NOTICE: PHP message: PHP Warning:  Can't preload already declared class ReflectionEnum in /var/www/koillection/vendor/laminas/laminas-code/polyfill/ReflectionEnumPolyfill.php on line 8
I have thrown the latest flag and still looks to be present. I can then still hit the webUI but when I go to create the initial user and I hit submit I receive the following error.
The CSRF token is invalid. Please try to resubmit the form.

**Comment by benjaminjonard** [comment]
Hello, this two problems are unrelated, could you have a look at this issue #341 ?

**Comment by benjaminjonard** [comment]
Latest Docker images should fix the unhealthy container. Closing for now but don't hesitate to reopen if the problem persists.
